---
- name: Install Jenkins
  hosts: Jenkins-Controller
  become: yes
  tasks:
    - name: Update Packages
      apt:
        update_cache: yes
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
    - name: Add Jenkins Keys
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    - name: Add Jenkins Repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Start Jenkins
      service:
        name: jenkins
        state: started
    - name: Auto Start Jenkins
      service:
        name: jenkins
        enabled: yes




- name: Configure Jenkins Slave
  hosts: Jenkins-Slave
  become: yes
  tasks:
  - name: Update Packages
    apt:
      update_cache: yes
  - name: Install Java 17
    apt:
      name: openjdk-17-jdk
      state: present
